# Generated by Django 5.1.6 on 2025-03-03 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfc', '0005_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Block', 'Block')], default='Active', max_length=255, null=True),
        ),
    ]
