# Generated by Django 5.1.6 on 2025-03-03 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfc', '0008_templates_users_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='approval_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=255, null=True),
        ),
    ]
