# Generated by Django 5.1.6 on 2025-03-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfc', '0009_users_approval_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('validity', models.IntegerField(blank=True, help_text='Validity in days', null=True)),
            ],
        ),
    ]
