# Generated by Django 5.1.6 on 2025-03-03 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfc', '0011_subscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribers',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nfc.users'),
        ),
    ]
