# Generated by Django 5.1.6 on 2025-03-03 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfc', '0012_alter_subscribers_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfc.vendor'),
        ),
    ]
