# Generated by Django 5.1.6 on 2025-03-03 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfc', '0013_users_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribers',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
