# Generated by Django 5.1.6 on 2025-03-03 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfc', '0015_users_amount_users_balance_users_paid_users_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='users',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='users',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='users',
            name='plan',
        ),
        migrations.CreateModel(
            name='Receivables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfc.subscription')),
            ],
        ),
    ]
