# Generated by Django 5.1.6 on 2025-03-03 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfc', '0016_remove_users_amount_remove_users_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivables',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nfc.users'),
        ),
        migrations.AlterField(
            model_name='receivables',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mode', models.CharField(blank=True, choices=[('Bank', 'Bank'), ('Cash', 'Cash'), ('G Pay', 'G Pay')], default='Bank', max_length=255, null=True)),
                ('received', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfc.receivables')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nfc.users')),
                ('vendor_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfc.vendor')),
            ],
        ),
    ]
