# Generated by Django 5.1.6 on 2025-03-03 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfc', '0017_receivables_user_alter_receivables_balance_income'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receivables',
            old_name='paid',
            new_name='pay',
        ),
        migrations.AddField(
            model_name='receivables',
            name='mode',
            field=models.CharField(blank=True, choices=[('Bank', 'Bank'), ('Cash', 'Cash'), ('G Pay', 'G Pay')], default='Bank', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='receivables',
            name='received',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='receivables',
            name='vendor_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfc.vendor'),
        ),
        migrations.DeleteModel(
            name='Income',
        ),
    ]
