# Generated by Django 5.1.6 on 2025-03-17 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nfc', '0019_expenses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='template',
        ),
        migrations.DeleteModel(
            name='Templates',
        ),
    ]
