# Generated by Django 5.1.6 on 2025-03-17 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfc', '0020_remove_users_template_delete_templates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='users',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='users',
            name='youtube',
        ),
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media_links', to='nfc.users')),
            ],
        ),
    ]
