# Generated by Django 5.1.7 on 2025-03-19 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfc', '0021_remove_users_facebook_remove_users_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_logos/'),
        ),
    ]
